index_col: 'id'
target_col: 'price'
n_splits: 5
use_kfold: true  # true - использовать KFold, false - обычная кросс-валидация
seed: 42
scoring:
  - neg_mean_absolute_error
  - neg_mean_squared_error
  - r2